-- begin ALERTSYSTEM_ALERT_SNOOZE
alter table ALERTSYSTEM_ALERT_SNOOZE add constraint FK_ALERTSYSTEM_ALERT_SNOOZE_ALERT_TYPE foreign key (ALERT_TYPE_ID) references ALERTSYSTEM_ALERT_TYPE(ID)^
create index IDX_ALERTSYSTEM_ALERT_SNOOZE_ALERT_TYPE on ALERTSYSTEM_ALERT_SNOOZE (ALERT_TYPE_ID)^
-- end ALERTSYSTEM_ALERT_SNOOZE
-- begin ALERTSYSTEM_ALERT_TYPE
alter table ALERTSYSTEM_ALERT_TYPE add constraint FK_ALERTSYSTEM_ALERT_TYPE_FROM_PROCESS foreign key (FROM_PROCESS_ID) references ALERTSYSTEM_PROCESS(ID)^
alter table ALERTSYSTEM_ALERT_TYPE add constraint FK_ALERTSYSTEM_ALERT_TYPE_TO_PROCESS foreign key (TO_PROCESS_ID) references ALERTSYSTEM_PROCESS(ID)^
create index IDX_ALERTSYSTEM_ALERT_TYPE_FROM_PROCESS on ALERTSYSTEM_ALERT_TYPE (FROM_PROCESS_ID)^
create index IDX_ALERTSYSTEM_ALERT_TYPE_TO_PROCESS on ALERTSYSTEM_ALERT_TYPE (TO_PROCESS_ID)^
-- end ALERTSYSTEM_ALERT_TYPE
